<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="5" ignored="0" total="23" passed="18" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-19T13:06:53 IST" name="Suite" finished-at="2025-06-19T13:07:15 IST" duration-ms="21396">
    <groups>
    </groups>
    <test started-at="2025-06-19T13:06:53 IST" name="Test" finished-at="2025-06-19T13:07:15 IST" duration-ms="21396">
      <class name="api.tests.UserTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:06:54 IST" name="setup" finished-at="2025-06-19T13:06:54 IST" duration-ms="329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_createUser()[pri:1, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:06:54 IST" name="test_createUser" finished-at="2025-06-19T13:06:59 IST" duration-ms="4796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_createUser -->
        <test-method retried="true" signature="test_getUserByName()[pri:2, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:06:59 IST" name="test_getUserByName" finished-at="2025-06-19T13:07:00 IST" duration-ms="1636" status="SKIP">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["id"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["id"] not found.
at org.json.JSONObject.get(JSONObject.java:635)
at api.tests.UserTests.test_getUserByName(UserTests.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method retried="true" signature="test_getUserByName()[pri:2, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:00 IST" name="test_getUserByName" finished-at="2025-06-19T13:07:02 IST" duration-ms="1764" status="SKIP">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["id"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["id"] not found.
at org.json.JSONObject.get(JSONObject.java:635)
at api.tests.UserTests.test_getUserByName(UserTests.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method retried="true" signature="test_getUserByName()[pri:2, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:02 IST" name="test_getUserByName" finished-at="2025-06-19T13:07:04 IST" duration-ms="1984" status="SKIP">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["id"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["id"] not found.
at org.json.JSONObject.get(JSONObject.java:635)
at api.tests.UserTests.test_getUserByName(UserTests.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method signature="test_getUserByName()[pri:2, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:04 IST" name="test_getUserByName" finished-at="2025-06-19T13:07:06 IST" duration-ms="1990" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method signature="test_updateUserByName()[pri:3, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:06 IST" name="test_updateUserByName" finished-at="2025-06-19T13:07:08 IST" duration-ms="1634" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_updateUserByName -->
        <test-method signature="test_deleteUserByName()[pri:4, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:08 IST" name="test_deleteUserByName" finished-at="2025-06-19T13:07:09 IST" duration-ms="1427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_deleteUserByName -->
        <test-method signature="test_loginUser()[pri:5, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:09 IST" name="test_loginUser" description="This test verifies that logging in a user returns a 200 status code" finished-at="2025-06-19T13:07:13 IST" duration-ms="3649" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_loginUser -->
        <test-method signature="test_logoutUser()[pri:6, instance:api.tests.UserTests@7d64e326]" started-at="2025-06-19T13:07:13 IST" name="test_logoutUser" description="This test verifies that the logout response returns a 200 status code" finished-at="2025-06-19T13:07:15 IST" duration-ms="1935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_logoutUser -->
      </class> <!-- api.tests.UserTests -->
      <class name="api.tests.DDTests">
        <test-method signature="test_DDT_createUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:06:55 IST" name="test_DDT_createUser" data-provider="ExcelData" finished-at="2025-06-19T13:06:58 IST" duration-ms="2806" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[2010]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testuser1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Canedy]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[a@gmail.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[test@1]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[8687809765]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_createUser -->
        <test-method signature="test_DDT_createUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:06:58 IST" name="test_DDT_createUser" data-provider="ExcelData" finished-at="2025-06-19T13:07:00 IST" duration-ms="1858" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[2011]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testuser2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Kim]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Kom]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[b@gmail.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[test@2]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[8687809565]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_createUser -->
        <test-method signature="test_DDT_createUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:07:00 IST" name="test_DDT_createUser" data-provider="ExcelData" finished-at="2025-06-19T13:07:01 IST" duration-ms="1681" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[2012]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testuser3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Smith]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Steve]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[c@gmail.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[test@3]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[8687309765]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_createUser -->
        <test-method signature="test_DDT_deleteUsers(java.lang.String)[pri:4, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:07:01 IST" name="test_DDT_deleteUsers" data-provider="UserNames" finished-at="2025-06-19T13:07:03 IST" duration-ms="1833" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[testuser1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_deleteUsers -->
        <test-method signature="test_DDT_deleteUsers(java.lang.String)[pri:4, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:07:03 IST" name="test_DDT_deleteUsers" data-provider="UserNames" finished-at="2025-06-19T13:07:05 IST" duration-ms="2002" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[testuser2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_deleteUsers -->
        <test-method retried="true" signature="test_DDT_deleteUsers(java.lang.String)[pri:4, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:07:05 IST" name="test_DDT_deleteUsers" data-provider="UserNames" finished-at="2025-06-19T13:07:07 IST" duration-ms="1480" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[testuser3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.tests.DDTests.test_DDT_deleteUsers(DDTests.java:42)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_deleteUsers -->
        <test-method signature="test_DDT_deleteUsers(java.lang.String)[pri:4, instance:api.tests.DDTests@5629510]" started-at="2025-06-19T13:07:07 IST" name="test_DDT_deleteUsers" data-provider="UserNames" finished-at="2025-06-19T13:07:08 IST" duration-ms="1522" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[testuser3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DDT_deleteUsers -->
      </class> <!-- api.tests.DDTests -->
      <class name="api.tests.UserTests2">
        <test-method is-config="true" signature="setup()[pri:0, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:06:54 IST" name="setup" finished-at="2025-06-19T13:06:54 IST" duration-ms="329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_createUser()[pri:1, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:06:54 IST" name="test_createUser" finished-at="2025-06-19T13:06:59 IST" duration-ms="4796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_createUser -->
        <test-method retried="true" signature="test_getUserByName()[pri:2, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:06:59 IST" name="test_getUserByName" finished-at="2025-06-19T13:07:00 IST" duration-ms="1710" status="SKIP">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["id"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["id"] not found.
at org.json.JSONObject.get(JSONObject.java:635)
at api.tests.UserTests2.test_getUserByName(UserTests2.java:128)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method signature="test_getUserByName()[pri:2, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:07:00 IST" name="test_getUserByName" finished-at="2025-06-19T13:07:02 IST" duration-ms="1777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method signature="test_updateUserByName()[pri:3, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:07:02 IST" name="test_updateUserByName" finished-at="2025-06-19T13:07:04 IST" duration-ms="1927" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_updateUserByName -->
        <test-method signature="test_deleteUserByName()[pri:4, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:07:04 IST" name="test_deleteUserByName" finished-at="2025-06-19T13:07:06 IST" duration-ms="1792" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_deleteUserByName -->
        <test-method signature="test_loginUser()[pri:5, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:07:06 IST" name="test_loginUser" description="This test verifies that logging in a user returns a 200 status code" finished-at="2025-06-19T13:07:07 IST" duration-ms="1524" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_loginUser -->
        <test-method signature="test_logoutUser()[pri:6, instance:api.tests.UserTests2@13f95696]" started-at="2025-06-19T13:07:07 IST" name="test_logoutUser" description="This test verifies that the logout response returns a 200 status code" finished-at="2025-06-19T13:07:09 IST" duration-ms="1463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_logoutUser -->
      </class> <!-- api.tests.UserTests2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
